version: '3'
services:
  app:
    container_name: docker-node
    restart: always
    build: .
    ports: 
      - '4000:4000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27018:27017'  